controller_list:
  - name: rm_75
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - joint7
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
  - name: dh_gripper
    action_ns: gripper_action
    type: GripperCommand
    default: True
    joints:
      - finger_joint
initial:  # Define initial robot poses per group
  - group: cobot_arm
    pose: zero

# /gazebo_ros_control:   
#     pid_gains:
#       joint1:
#         p: 1.0
#         i: 0.0 
#         d: 0.0
#       joint2:
#         p: 1.0
#         i: 0.0 
#         d: 0.0
#       joint3:
#         p: 1.0
#         i: 0.0 
#         d: 0.0
#       joint4:
#         p: 1.0
#         i: 0.0 
#         d: 0.0
#       joint5:
#         p: 1.0
#         i: 0.0 
#         d: 0.0
#       joint6:
#         p: 1.0
#         i: 0.0 
#         d: 0.0
#       joint7:
#         p: 1.0
#         i: 0.0 
#         d: 0.0
